Switch communication from createEvent to postMessage
jointoucan/finch-graphql pull request #175
Opened 2021-07-29 19:37 UTC by zeckdude

## Description

Firefox doesn't allow communicate with the content script via dispatchEvent so we need use `window.postMessage` instead.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#communicating_with_the_web_page

## Testing

- [X] Includes test.
- [ ] Manually tested.

## Additional notes

I didn't actually add any tests but after the changes the current tests still works.

2021-07-29 21:04 UTC, jcblw commented
Still needs verification on Safari if we can use this method exclusively. I am assuming yes, but we really need to test it out.

```
finch-graphql@1.2.1-alpha
```

Published this version to do this testing.

2021-07-30 00:27 UTC, jcblw commented
> Still needs verification on Safari if we can use this method exclusively. I am assuming yes, but we really need to test it out.
> 
> ```
> finch-graphql@1.2.1-alpha
> ```
> 
> Published this version to do this testing.

Verified this does in fact work on Safari, as well. Think we should eventually should rename, fear that is some breaking changes though.

2021-07-30 00:27 UTC, jcblw commented on packages/finch-graphql/src/external/listenForDocumentQueries.ts
> +  // document.addEventListener(FinchDocumentEventNames.Request, onMessage);
Can we remove this line.

2021-07-30 00:28 UTC, jcblw requested changes
One super minor change, just remove the commented out code and I can make a release for this.

2021-07-30 00:42 UTC, zeckdude commented
I have removed the line. Thanks @jcblw

2021-07-30 00:44 UTC, jcblw approved these changes

2021-07-30 15:35 UTC, merged